### PR TITLE
Add support to dynamically fetch PR if config file not present

### PR DESCRIPTION
**Pull request by arush-sal**
Signed-off-by: Arush Salil <me@aru.sh>

### CODE REVIEW

**Comment by dlvhdr** [comment]
Hi @arush-sal :)
Can you please provide more information on what this pull request does?

* Please provide a screenshot or even better a video of how the new flow looks/works.
* What's the use case for this?

**Comment by arush-sal** [comment]
@dlvhdr 
*What this pull request does:*
* It removes the mandate need to have a static config file defining your repos

*How the new flow looks like:*
* Typically it doesn't change anything in the flow except that now you don't necessarily need to create the config file for this to work.

*What's the use case for this?*
* For people with too large of dynamic repo set that they can't have a stick config file and hence want to track all the recent PRs for them/in their profile.

**Comment by dlvhdr** [comment]
I'm working on removing the repo list requirement and think it will solve that for you. 
The approach you suggest will make it so new users start with prs from their notifications which is nit something I want. 
I would like to have a default config file. 
Once I allow not to pass the repos list, that will be easy to do.

**Comment by dlvhdr** [comment]
See https://github.com/dlvhdr/gh-prs/pull/40

**Pull request closed without merging**
